FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_LANDINGPAGE_URL
ENV NEXT_PUBLIC_LANDINGPAGE_URL=$NEXT_PUBLIC_LANDINGPAGE_URL

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./

EXPOSE 3001

CMD ["npm", "run", "start"]
